name: Release

on:
  release:
    types: [created]
    
jobs:
  release-windows-386:
    name: release windows/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_TOKEN }}
        GOARCH: "386"
        GOOS: windows
        CMD_PATH: main.go
        EXTRA_FILES: "LICENSE"
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB}}
        GOARCH: amd64
        GOOS: windows
        CMD_PATH: main.go
        EXTRA_FILES: "LICENSE"
