name: Release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
        
    steps:
      - uses: actions/checkout@v4
      - name: Build Binaries
        uses: wangyoucao577/go-release-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.22.1
          build_command: main.go
                  
      - name: Package Directories and Files
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: .
          exclude: .git* .idea*
          if-no-files-found: error
